---
- name: SHOW CDP
  ios_command:
    commands:
      - show cdp neighbors detail
  register: version

- name: PARSE CDP
  command_parser:
    file: "parsers/ios_cdp.yml"
    content: "{{ version.stdout.0 }}"